plugins {
    antlr
}

dependencies {
    // ANTLR
    antlr("org.antlr:antlr4:4.13.1")

    // JPA
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")
}

tasks {
    compileKotlin {
        dependsOn(generateGrammarSource)
    }

    compileTestKotlin {
        dependsOn(generateTestGrammarSource)
    }

    sourcesJar {
        dependsOn(generateGrammarSource)
    }

    jacocoTestReport {
        // Exclude the Dynamic Query's DSL files from the JaCoCo reports since such source is
        // generated by the ANTLR (without the Generated annotation)
        val filteredFiles = classDirectories.files.map {
            fileTree(it).exclude("br/com/dillmann/dynamicquery/core/grammar/dsl/**")
        }

        classDirectories.setFrom(filteredFiles)
    }
}
