name: dynamic-query-pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 11
          distribution: temurin
      - name: detekt
        run: ./gradlew detekt

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 11
          distribution: temurin
      - name: unit-tests
        run: ./gradlew test
