name: dynamic-query-main-pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: temurin
      - name: Sonar cache
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: sonar-cache
          restore-keys: sonar-cache
      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-cache
          restore-keys: gradle-cache
      - name: Unit tests
        run: ./gradlew test jacocoTestReport
      - name: Detekt
        run: ./gradlew detekt
      - name: Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
