name: dynamic-query-release-pipeline
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-to-maven-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: temurin
      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: gradle-cache
          restore-keys: gradle-cache
      - name: Publish to Maven Central
        run: ./gradlew assemble publishAggregatedPublicationToCentralPortal
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_SIGNING_KEY: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY }}
          MAVEN_CENTRAL_SIGNING_SECRET: ${{ secrets.MAVEN_CENTRAL_SIGNING_SECRET }}
